name: Build of Docker images

on:
  release:
    types: [published]
  push:
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: build-docker-image
  cancel-in-progress: false

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clean working directory
        uses: AutoModality/action-clean@v1.1.0
      - name: Delete unnecessary folders to free disk space
        run: |
          rm -rf /opt/hostedtoolcache
          rm -rf /usr/local/android /usr/share/dotnet /usr/local/share/boost /opt/ghc
          docker system prune --all --volumes --force
      - name: Checkout out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest package version
        shell: bash
        run: |
          latest_version=$(git tag -l 'v[0-9]*\.[0-9]*\.[0-9]*' | sort | tail -1)
          echo "latest_version=${latest_version:1}" >> $GITHUB_ENV
      - name: Build and push a docker image with pointtree installation (version tag)
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: josafatburmeister/pointtree:${{ env.latest_version }}-torch2.4.0-cuda12.4
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          dockerfile: Dockerfile
          context: .
      - name: Build and push a docker image with pointtree installation (latest tag)
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: josafatburmeister/pointtree:latest
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          dockerfile: Dockerfile
          context: .
      - name: Clean up docker build remains
        run: docker system prune --all --volumes --force
