name: Build of Docker images

on:
  release:
    types: [published]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: build-docker-image
  cancel-in-progress: false

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clean working directory
        uses: AutoModality/action-clean@v1.1.0
      - name: Delete unnecessary folders to free disk space
        run: |
          rm -rf /opt/hostedtoolcache
          rm -rf /usr/local/android /usr/share/dotnet /usr/local/share/boost /opt/ghc
          docker system prune --all --volumes --force
      - name: Checkout out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get latest package version
        shell: bash
        run: |
          latest_version=$(git tag -l 'v[0-9]*\.[0-9]*\.[0-9]*' | sort | tail -1)
          echo "latest_version=${latest_version:1}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            josafatburmeister/pointtree:${{ env.latest_version }}-torch2.10.0-cuda12.9
            josafatburmeister/pointtree:latest
      - name: Clean up docker build remains
        run: docker system prune --all --volumes --force
