
name: CI pipeline for pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/code-quality.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      update-coverage-badge: true
