name: CI pipeline for main branch
on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/code-quality.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      update-coverage-badge: false
